
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: customer_db
      MYSQL_USER: cdp_user
      MYSQL_PASSWORD: cdp_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer-ui
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:
